version: "3.7"

services:
  gateway:
    build: .
    container_name: gateway-iot
    ports:
      - 1880:1880
      - 1885:1885
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config:/data
    networks:
      - network-name

networks:
    network-name:
      name: uniovi
